quotes := map[string]string{
	"Give a man an 0day and he'll have access for a day, teach a man to phish and he'll have access for life.": "the grugq",
	"You can't fight a meme with an exploit.": "the grugq",
	"Cyber warfare isn't chess, it's calvinball.": "the grugq",
	"An APT is not a toolchain. You can't download your way to parity with Ft Meade.": "the grugq",
	"OPSEC is a process, not a tool set": "the grugq",
	"Finding the right level of paranoia is an operational challenge": "the grugq",
	"0days are offensive security by obscurity.

Just as fragile for attackers as “security by obscurity” is for defenders.": "the grugq",
	"“If you want to conceal something, don’t swear people to silence, tell as many alternative stories as possible.” -- SOE rule": "the grugq",
	"I think the American way of cyberwar is: “it is statistically impossible to make mistakes 100% of the time, plus law of large numbers, so…”": "the grugq",
	"grugq’s law is: don’t attribute to exploits what can adequately be explained by password theft.": "the grugq",
	"The P in APT doesn’t stand for “Pathetic”": "the grugq",
	"Relying on attacker incompetence is no way to go through life": "the grugq",
	"Offensive cyber’s real strategic (ie. continuing) advantage is a \"true positive\" success signal. Defenders must deal with this": "the grugq",
	"Only break one law at a time.": "the grugq",
	"Never lie by accident.": "the grugq",
	"ProTip: you’re not worth an 0day.": "the grugq",
	"Fear of 0day is like being terrified of ninjas instead of cardiovascular disease.": "the grugq",
	"I’m not going to advise you on how to break the law other than to suggest that you shouldn’t.": "the grugq",
	"Cyber is really only effective as an offensive capability. Defence has mitigation, detection, resilience, etc...but at the end of the day, cyber is a domain that favours the offensive (of course, once on someone else's network, you're on the defensive)": "the grugq",
	"Make compromises: cost more; yield less; harder to use; easier to find. Analyze them, & stay awake": "the grugq",
	"Fetishising 0day means that people think once a vulnerability is public there's some sort of automagic immunity.": "the grugq",
	"It's surprising how critical good phishing technique is with these APT attacks. Effective phishing is more important than 0day.": "the grugq",
	"I think I understand the US strategy against Chinese APT. It’s to flood the APT with so much data they won’t have analysts to review it all.": "the grugq",
	"The APT that can be named is not the real APT. The way of APT is vast and unknowable. The APT is everywhere & nowhere": "the grugq",
	"APT: repeatable success, interchangeable operators of low to mediocre skill. Easy to train techniques. Consistent results.

Like infantry.": "the grugq",
	"Metcalfe’s Law is a bitch.": "the grugq",
	"Limit the number of people involved to the bare minimum.": "the grugq",
	"“The less written down, the better” or, “never say or email anything you don’t want read out in a court of law”": "the grugq",
	"Never write if you can speak;
Never speak if you can nod;
Never nod if you can wink.": " Martin Lomasney",
	"If you think, don't speak.
If you speak, don't write.
If you write, don't sign.
If you sign, don't be surprised.": "Russian Joke",
	"A ruse is the subtlest means of attaining one's ends": "the suble ruse",
	"winning wars without battles.": "T.E Lawrence",
	"You can get 25% off a Mandiant incident response with the code: ITWASCHINA. 100% off if you just use that code as the report.": "the grugq",
	"Ransomware is not about encrypting data. It is the _current_ implementation of a methodology that coerces the victim to act as an agent for the criminal (typically to acquire BTC.) Encrypting data just an implementation detail; it’s the “coerced agent” part that matters. There are infinite ways to coerce someone once you have access to their data. People will pay more to keep their secrets from their friends than to regain access to their data.": "the grugq",
	"APT28 still going through about 2 0days a month, they don't stockpile, they burn.": "the grugq",
	"W/ the MySpace hack, people will understand that passwords are like condoms. Single use only.": "the grugq",
	"Trust relationships are the foundations of compromise.": "the grugq",
	"That marketing cycles around major conferences dictate when research is released tells you everything you need to know about infosec.": "the grugq",
	"People that need their software to work in order to make money invest more into engineering than those who don't. Think about that next time you buy enterprise security software. Unless you pay only after it has stopped attacks ;)": "the grugq",
	"An important lesson to learn is not to deploy tools before they are ready. The risk is revealing capability before you can exploit it": "the grugq",
	"That’s pretty amazing discipline from the attackers. They discard 5 9's of infections to focus on a tiny subset. No chance that’s criminals": "the grugq",
	"when your attribution is based exclusively on forensic artifacts, you're using only adversarial controlled data": "the grugq",
	"Drop 0day, not bombs.": "the grugq",
	"Are there any #pwn2own winners that aren’t sponsored by massive Chinese Internet companies? It’s the equivalent of a Google team winning. No doubt the teams are skilled, but this is just marketing for the Chinese audience. 'Tencent wins hacking competition!' 'Baidu wins...' Is it time to accept that #Pwn2Own has outlived its usefulness to the community? Companies paying each other for marketing... *yawn*": "the grugq",
	"AirCnC: It’s like AirBnB for botnets. Have a compromised host you don’t use all the time? Need a host but can’t afford the maintenance?": "the grugq",
	"Long uptime for security. No one ever tests their exploits against browsers with a week of uptime. Heap feng shui? More like heap makeover": "the grugq",
	"You are going to be phished long before you are going to be hit with CIA 0days. Enable 2FA and get a password manager.": "the grugq",
	"a key signing party is basically \"bring your children over to get infected with chicken pox\", but for grownup's laptops": "the grugq",
	"There are people with Tor browser 0day. This is a perennial truth. Learn to be secure even if the adversary has exploits. Because they do.": "the grugq",
	"A great way to mitigate TAO is to not be the elected leader of a nation state, #protip": "the grugq",
	"Journos assume we know to say 'off the record' and we assume they know not to click on 'Secret Doc.PDF.exe'": "the grugq",
	"In none of the targeted attacks me and @CDA observed against Iranian civil society we found a 0day used. Mostly no \"exploit\" at all in fact. Besides the usual .scr, we see a variety of Office tricks, and embedding of PowerShell in a variety of file formats (e.g. LNK) as well as repackaging of legitimate software. [...] Surely, there's a lot of human mistakes involved, but as long as we enable e.g. executing embedded EXEs through PowerPoint animations the human mistakes seem more tolerable, and development and employment of exploits way less \"profitable\". Most of the tricks I observe used for infection also have the \"advantage\" of requiring way less situational awareness from the attacker which significantly reduces costs and improve success rate for attackers [...] In some sadistic way, I wish we'd be in a place where exploits were really required, at least it would sensibly increase costs for attacks.": "the grugq",
	"less Twitter more committer! Keep coding": "the grugq",
	"Software is eating the world. Software rots. This is a very scary thing to think about.": "the grugq",
	"Everybody that's been breached or has security patches to release? Today is _the_ day to bury infosec news!": "the grugq",
	"New rule: if you are hacked via OWASP Top 10, you’re not allowed to call it 'advanced' or 'sophisticated.'": "the grugq",
	"Don’t make me sudo. You wouldn’t like me when I’m root.": "the grugq",
	"Long uptime for security. No one ever tests their exploits against browsers with a week of uptime. Heap feng shui? More like heap makeover": "the grugq",
	"There are people with Tor browser 0day. This is a perennial truth. Learn to be secure even if the adversary has exploits. Because they do.": "the grugq",
	"If TAO is in your threat model chances are you're terrible at threat modeling.": "the grugq",
	"Journos assume we know to say 'off the record' and we assume they know not to click on 'Secret Doc.PDF.exe'": "the grugq",
	"Encryption is a law enforcement problem, not an intelligence one.": "the grugq",
	"OH: International law is colonialism by other means.": "the grugq",
	"Laws make criminals. Repeal more laws, you get fewer criminals, they can use the law courts to settle contractual disputes rather than violence.": "the grugq",
	"snowden argues the same techy bullshit argument other geeks have: that tech can defeat law, so ignore policy. it's complete bullshit. It makes geeks feel powerful while not actually doing anything useful.": "the grugq",
	"They violate the primary rule of maintaining security against a nation state - don’t break the law.": "the grugq",
	"until geeks realize that people execute law code and not automatons, it’s kinda messy.": "the grugq",
	"Not everything is APT and not every APT is sophisticated. Focus on practicing basic IT governance — asset management, patching, network segmentation, least privilege, 2FA, logging... drop in some @ThinkstCanary. Make them work to earn their pay": "the grugq",
	"Real APT: we need to read their emails and steal their spreadsheets.
Fantasy APT: we need to hack their baseband…because reasons!": "the grugq",
	"Hey aspirational B team APT. You guys really need to learn that mission success is about the escape and evation, not the execution.": "the grugq",
	"Yeah, I’m just being stupid about bureaucracy and organizations these days. Wondering if there’s units that work to enable the dev teams (hack for certs, hack for source, hack for infrastructure) and so on. Just like an army isn’t all infantry, what elements make up an APT group?": "the grugq",
	"17 Malware Analysis Techniques That Work For Any APT Campaign.
#infoseccosmo": "the grugq",
	"cyber pathogen profilaxis is a common complication from APT infections.": "the grugq",
	"The phrase for today is: collection bias. We see only the ops that get caught in the sector that is being monitored. The view port on APT activity is limited and skewed. Our data sets suck.": "the grugq",
	"Wonder how much the style of attacks has to do with provenance. That is, pen testers mimic old school hackers, APT is repeatable success.": "the grugq",
	"Criminals and other APT groups will happily use anything that works, even if it is known.": "the grugq",
	"Which APT Campaigns Are Hot This Summer!

#infoseccosmo": "the grugq",
	"Interestingly the North Koreans are probably the only APT that views cyberwar in the same terms as the US, but they aren’t constrained": "the grugq",
	"TBF, there’s not much a civilian group can do to protect against an APT.": "the grugq",
	"Does anyone except Russian crooks & pen testers still do “Step 1: hack the server“ style pen tests? The world has standardized on APT right?": "the grugq",
	"This is like the APT starter pack: Flash, win33k, old Java *and* old office, everything a gov contracting house runs on every workstation!": "the grugq",
	"If I’m understanding this correctly, “cyber” is something you catch from a Chinese if you have unprotected APT?": "the grugq",
	"in peace, prepare for apt": "the grugq",
	"WTF is wrong with people? The opposition will use the cheapest most reliable tool every time they can. Yes, the GRU uses phishing (and 0day)": "the grugq",
	"Russia can afford to kill the opposition’s 0day, regardless of how good, because they don’t care much about stealth or preserving exploits.": "the grugq",
	"APTs use what works. But it’s kinda embarrassing if you don’t make them at least burn 0day...": "the grugq",
	"0day are for hardened HVT. Like spices, you don’t want to over use them, just enough": "the grugq",
	"I’ll concede it isn’t perfect or feasible in every case, but I think “decruitment” is a totally viable offensive technique in a variety of situations. It is a variant of “countering violent extremism” in a way. Provide an off ramp, throw in incentives (if possible)": "the grugq",
	"Any competent offensive cyber team is going to need to detect whether they’ve popped a compromised box. They need a simple operational tool that works and doesn’t leak intelligence about what they know regarding other teams’ tooling —because it is run on a compromised host.": "the grugq",
	"Reminder to everyone: [bug bounties use] market forces to secure things by raising the cost of offensive ops, not the cost of defence.": "the grugq",
	"Create infrastructure that requires only a new $5 VPS and a “rake deploy” to replicate to a new system. Offensive DevOps": "the grugq",
	"APT groups operational characteristics are the result of organizational make up which is the result of politics & history.": "the grugq",
	"Defender's strategic advantage is visibility at vantage points & scale unavailable & unknown to attackers. Denial of certainty of stealth. -- @dinodaizovi": "the grugq",
	"Modern day alchemy: turn a nothing burger wiki dump into an information operation.": "the grugq",
	"Phrack, uniformed, etc are the alchemical grimoires of cyber security. Practitioners scribbling down what they knew from experiments and presenting the knowledge to their peers. They’re presented authoritatively, rich w/ arcane detail, on the path to professional discipline
As an industry we still don’t know how to produce “hacker enlightenment” other than walking the old paths. Some of the Services have developed private colleges for professionalized training, but even they aren’t reliable at creating “master” hackers.
Hacking is beyond the “alchemy” phase, but it’s not yet “chemistry.” Is it just gonna take more time? What would we need to bridge that gap?": "the grugq",
	" cyber is calvinball. The only rule is that it’s never played the same way twice.": "the grugq",
	" We're only at the Alchemy stage of security - it's not a real science yet.": "the grugq",
	" If a nation state is after you, you’re going to have a bad time.": "the grugq",
	"The Internet is the Wild West. We thought we were the cowboys but it turns out we're the indians. Fuck.": "the grugq",
	"Learning good OPSEC requires internalizing the behavioural changes required to continually maintain a strong security posture.": "the grugq",
	"Attackers are resource constrained too. ": "Dino Dai Zovi",
	"Attackers have bosses and budgets too.": "Phil Venables",
	"Your perimeter is not the boundary of your network, it's the boundary of your telemetry.": "the grugq",
	"The future of CNO is the Morris Worm from 1988.": "the grugq",
	"Core offensive methodologies exploit human factors. Decades of success prove they aren't going away.": "the grugq",
	"[a cyber offence framework] does not cost an aircraft carrier as Aitel says, it costs a submarine.": "the grugq",
	"\"Happy birthday @miaubiz!\" -- the birthday attack.": "the grugq",
	"No one is going to jail for you.": "the grugq",
	"The ultimate goal of strategem is to make the enemy quite certain, very decisive, and wrong. ": "Barton Whaley",
	"The Russians are playing chess and the Americans are playing “how far does this crayon go up my nose?”": "the grugq",
	"“The more security, the more bizarre the method of escape must be.”": "Forrest Tucker, bank robber, stickup man, prison escape artist",
	"Propaganda is marching orders for the faithful rather than a tool of persuasion for the uncommitted": "the grugq",
	"Force and fraud in war are the two cardinal virtues.": "Hobbes",
	"No good men among the living, no bad men among the dead.": "afghan saying",
	"War is very simple, but the simplest thing is very hard.": "Clausewitz",
	"A powerful army can only fight one battle at a time, but the *idea*of a powerful army can intimidate any number of enemies all at once.": "Bret Devereaux",
	"the prediction is more important than the fact": "Bernard Brodie",
	"People want to hear things that confirm their views, not challenge them.": "",
	"GRU (\"Head Office for Enlightenment\")": "Google Translate",
	"Security is in inverse proportion to the square of the number of people who know. ": "",
	"in this job, if you are not passionate, you can't succeed. you need to be reckless and relentless and never give up, that's what gives results in the end": "hacker",
	"every army recreates the order of the society it comes from on the battlefield": "",
	"The benefit of controlling a modern state is less the power to persecute the innocent, more the power to protect the guilty.": "",
	"Convenience changes convention.": "",
	"This is so true - and it's one of the hardest things to make students believe when I teach propaganda. Propaganda is most effective when it's verified & accurate. It's selected truths - \"emotionally potent oversimplifications\" (Noam Chomsky) - not lies. ": "",
	"The best propaganda is true. The British propagandists went to extraordinary lengths to ensure they “never lied by accident.” Goebbels’ rules for propaganda require truth. Every PSYOP, deception, IO manual explains how to use the truth to maximum effect.": "",
	"OPSEC is a process not a toolset.": "the grugq",
	"Cover.
Concealment.
Compartmentation.
Isolation.
Distance in space and time.
Layered defence.
Meticulous caution.
Boring is better.": "",
	"On why hackers win": "thegrugq_ebooks",
	"And retaliating against civilian populations is classic genocidal murder, which you know, the classics are the classics for a reason.": "thegrugq_ebooks",
	"Assume
Orient 
Decide
Purchase

The more realistic OODA loop in infosec.": "the grugq",
	"Will need to cyber again.": "thegrugq_ebooks",
	"Success can not be advertised; failure cannot be explained. ": "Eisenhower, on espionage",
	"A nation is a group of people united by a mistaken view about the past and a hatred of their neighbors.": "Karl Deutsch",
	"Behind every incident is a human being and a business model.": "the grugq",
	"OH: cryptographers call this “real world attacks,” and it is outside their threat model…": "",
	"Opsec will get you through times of no crypto better than crypto will get you through times of no opsec": "the grugq",
	"Two eternal truths:
1) compartmentation is the foundation of security
2) trust relationships are the foundation of compromise": "the grugq",
	"The best advice is almost never a list of tools. Knowing the three Cs of operational security is more useful than “Use Signal, Use Tor”

• Cover
• Concealment
• Compartmentation
": "the grugq",
	"Typical compartmentation failure. Architect for security failure. As always.": "",
	"Compartmentation failure. Bad COMSEC. Poor choice in enemies.": "",
	"hence compartmentation, cover, concealment, and the rapid recovery process. Planning to never fail is failure to plan": "",
	"Compartmentation: operational security term for \"how big the shit sandwich will be\" when everything else fails.
Keep your shit sandwich bite sized": "",
	"compartmentation means \"inefficiency\" and that can be damn painful.": "",
	"Cover, concealment, compartmentation.
Capability, intent, opportunity.

The foundations of operational security.": "the grugq",
	"Compartmentation complicates correlation. So do time deltas. Use both.": "the grugq",
	"Protect: the op, its significance, operatives' identities
From: the public, LEO, Intel Agencies
Using: cover, concealment, compartmentation": "",
	"Apply the defensive counterintelligence principle of compartmentation, consistently, flexibly and adaptively in your daily operations.
How fucking difficult is it to take a principle and use it? Don’t get so hung up on implementation details, those can and should be altered
Any static operational security plan will have vulnerabilities that can be exploited by the adversary. Don’t rely on someone else’s guide
Anything specific is too detailed, and bound to be wrong. Effective security requires adaptation to the context in which it is required.": "",
	"Compartmentation and cover are the alpha and omega of secret work. Everything else is just a tool. And don't forget to STFU.": "",
	"At the end of a war you need some soldiers left or else it looks like you’ve lost. ": "General Miller, \"In the Loop\"",
	"Total war means total victory, or total defeat.": "The Allure of Battle",
	"Fortune can give us no greater gift than discord among our enemies.": "Tacitus",
	"OPSEC: pay upfront, or layaway for years.": "the grugq",
	"The sins of OPSEC are paid in pain": "the grugq",
	"Truely anonymous finances mask a multitude of OPSEC sins.": "the grugq",
	"Your phone is not your friend. Your phone is a cop.": "Brandon Downey",
	"Strategy, n: to fight the Devil.": "Aelkus ",
	"The OPSEC that can be summarized as “just use this tool” is not the true OPSEC.": "the grugq",
	"Trying to \"tool\" your way to good OpSec is like trying to buy your way to a secure network. You can't \"tech\" yourself into security.": "the grugq",
	"If an OPSEC guide mentions a crypto *tool*, the guide is garbage.": "the grugq ",
	"\"You will kill ten of us. and we will kill one of you, but you will tire of it first\"": "Ho Chi Minh ",
	"Garry Kasparov once said that one of biggest mistakes chess players make is trying to 'undo' a bad move, when in reality, once a bad move is played, it is already a whole new game and an entirely fresh mindset is required. , ": "",
	"When things go wrong, don't go with them.": "Elvis Presley ",
	"Absence of evidence is evidence of cyber.": "the grugq ",
	"Ubiquity is the weapon.": "Dave Aitel",
	"Attackers use your infrastructure. Make it a sensor with event collection.  It’s not the bite that makes a spider successful–it’s the web.": "John Lambert @JohnLaTwC",
	"A rascal's work is never done.": "",
	"Total war means total victory, or total defeat": "",
	"The first rule of unrestricted war is that the are no rules. Nothing is forbidden.": "PLA",
	"Fortune can give us no greater gift than discord among our enemies.": "tacitus",
	"Trust neither fate, luck, nor the competence of others.": "",
	"Did something strange for a little bit of change.": "",
	"Striking first is half the game.": "",
	"Crime-terror nexus in the cyber domain": "",
	"We’d worry a lot less about what other people think of us if we realized how seldom they do": "Derren Brown",
	"When I keep my mouth shut I know what I am talking about.": "",
	"stealing intellectual property isn’t the same as stealing, say, a car; both the victim and the thief can continue to enjoy the benefits of the technology, just not the benefits of exclusivity.": "",
	"I trust my senses, but not my brain...": "",
	"We got them right where they want us.": "",
	"Teach someone to encrypt and they'll encrypt their traces; teach them how to OPSEC and there'll be no traces.": "@joernchen",
	"The only thing stopping them is law, and what is law but a threat?": "",
	"deployment of verifiable facts, evidence, precise information, appropriate tone, narrative coherence, targeting, covert motives, chronological disruption and repetition to construct the key elements [to craft black propaganda]": "Beatriz Lopez",
	"A great story is true. Not necessarily because it’s factual, but because it’s consistent and authentic.": "Seth Godin",
	"Hacker ProTip: take Chinese New Year off so all your hacking will be attributed to the PLA.": "the grugq",
	"\"Unpreventable\" is code for 'not responsible because the adversary was more motivated to win than we were to defend": "the grugq",
	"Neither blinded by the cloak nor dazzled by the dagger": "the grugq",
	"After Chaucer there is only Shakespeare. After Sun Tzu there is only commentary.": "the grugq",
	"The algorithm is not the problem; the algorithm is an expression of the problem": "Jennifer Cobbe",
	"Никогда такого не было, и вот опять. (It never happened, and here it is again.)": "Russian saying",
	"Amateurs practice until they get it right. Professionals practice until they can't get it wrong.": "",
	"Learning to fight in the dojo is like learning to swim on land.": "Hara kiri",
	"[t]he sum of the activities in which a government engages for the attainment of its objectives without unleashing armed warfare. But it is a description which applies to none of those activities when each of them is carried on independently of the others. In that case they become ‘mere’ diplomacy, intelligence, propaganda, economic negotiation, armament production, and so on. The essence of political warfare is that it is planned and the means employed to carry it on are coordinated.": "Lewis Galantiere, (1952) Head of Propaganda Policy at Radio Free Europe ",
	"You don't want your adversary providing your critical communications infrastructure": "the grugq",
	"any theory which asserts an ‘Asiatic’ mode of anything is pretty much guaranteed to be nonsense; Asia is, as veteran Risk players will know, very big and consequently extremely diverse": "Bret Devereaux",
	"Cultivate hacker mind, in the mind of a security expert there are a few possibilities. In the mind of a hacker, there are many": "the grugq",
	"It is never wise to let the enemy get used to a certain form of warfare; it is necessary to vary constantly the places, the hours and the forms of operation.": "Che",
	"Gentlemen, I don't know whether we are going to make history tomorrow, but at any rate we shall change geography. — The night before blowing the deep mines at the opening of the Messines Battle on June 7 1917": "General \"Tim\" Harrington",
	"Operational distinctions matter.": "JD",
	"Algorithms that maximize engagement also maximize enragement": "Halvar Flake (aka Thomas Dullien)",
	"people choose beliefs and systems of belief to fulfill a function for them.": "Halvar Flake (aka Thomas Dullien)",
	"People tend to believe in things that help them. [where that belief provides them with benefits]": "Halvar Flake (aka Thomas Dullien)",
	"People are very good at identifying what they want, and what is beneficial to them. People like to feel good about themselves and about what they do. The result is they tend to pick beliefs and systems of belief that: ... allow them to do what they want to do.  ... allow them to reap benefits. ... allow them to feel good about themselves at the same time.": "Halvar Flake (aka Thomas Dullien)",
	"Facebook is the search interface for people, Amazon for things, and Google for facts.": "Charles Stross",
	"Collapse is just a series of ordinary days in between extraordinary bullshit, most of it happening to someone else.": "Indi samarajiva ",
	"I don't have a horse in that fight.": "Dr Raid. (Brandon Edwards)",
	"Grab life by the low hanging fruit ": "Mtanji ",
	"Hindsight is 80/20": "Mtanji",
	"Hindsight is 50/50": "",
	"That horse has sailed": "Jay Lagario",
	"[In Cyber] Humans dominate the capability sphere ": "Dave Aitel (?)",
	"Not everyone's the same, but most people are.": "",
	"We wanted the best, but it turned out like always.": "Viktor Chernomyrdin",
	"It has never been like this and now it is exactly the same again": "Viktor Chernomyrdin",
	"Better than vodka, there is nothing worse.": "Viktor Chernomyrdin",
	"The enemy knows the system.": "Claude Shannon",
	"there is a fundamental asymmetry between order and chaos, and chaos always has the advantage in tempo.": "Aaron Rabinowitz ",
	"“The best place to get lost isn’t somewhere. It’s everywhere.” ": "Excerpt from Empire City Matt Gallagher",
	"practice is better than empty art, for practice is fully sufficient without art but art is not fully sufficient without practice.": "Johannes Liechtenauer",
	"Real apocalypse survival is keeping the school lunch system going.": "0xabad1dea",
	"It's crazier than a Kremlin-backed conspiracy": "Noah Shachtman",
	"information...consumes the attention of its recipients": "Herbert A. Simon (Nobel prize winner)",
	"Your cyber systems continue to function and serve you not due to the expertise of your security staff but solely due to the sufferance of your opponents": "Brian Snow",
	"Człowiek nigdy nie jest samotny, ktoś go przecież pilnuje.” (Lec)  //  It is hard to translate this aphorism with all the undertones of „pilnować”, but approximating: “A man is never truly lonely for there’s always someone keeping tabs on him.” — the great aphorist S. J. Lec.": "",
	"the man who first flung a word of abuse at his enemy instead of a spear was the founder of civilisation.’": "John Hughlings Jackson",
	"Stab fast, stab furious, and most importantly, stab first. ": "Sudanese mercenary ",
	"The operational environment shapes the operational security. This is a problem when a lax environment encourages weak security, because the environment can change but the security mistakes are forever. Mistakes only accrue. ": "The grugq",
	"You can fire your CISO, but you can't fire your problem ": "@spierenburg",
	"Aft, the most honour, forward, the better man. (18th century Royal Navy saying. Officers left in the back, sailors in the front)": "",
	"“As Sumner put it: the great motives that move people to social activity—including fighting—are hunger, love, vanity, and fear of superior powers”": "“William Graham Sumner, ‘War’ (1911)”",
	"You can never fight exactly as planned. You just do the best you can with all you've got.": "Terunofuji, ozeki sumo wrestler ",
	"Either seem as you are or be as you seem": "Rumi ",
	"The first step of any project is to grossly underestimate its complexity and difficulty.": "Nicoll Hunt @nicollhunt",
	"You can only be betrayed by someone you trust.": "John Le Carr",
	"I think that basically if you are considering a system that’s not used by terrorists and pedophiles you’re about to fail.": "Ben Nagy",
	"Everything I do is a norm. Everything they do is a crime.": "Grugq",
	"The maginot line worked perfectly. Not one German tank managed to penetrate it. Why, I think we could say the maginot line was a best of breed solution. Sure, there may have been some issues on the edges, with integrating legacy systems and covering non standard setups, but the core worked flawlessly! If anything, the problem was that it wasn't deployed widely enough. ": "Grugq",
	"Without trust, there can be no betrayal. ": "Grugq, cribbed from le Carre",
	"I’ll wreck you so hard you won’t even know what happened. I mean, literally, you won’t know anything happened….": "Grugq",
	"Einstein argued that there must be simplified explanations of nature, because God is not capricious or arbitrary. No such faith comforts the software engineer.": "Brooks (Mythical Man Month)",
	"Everybody warns you how terrible it is when they kill your 0days. Nobody warns you how horrible it is to maintain them for years across 20 versions, 4 OS, 3 allocators and 2 ISAs.": "Yannal ",
	"We wanted the best, but it turned out like always": "former Russian prime minister Viktor Chernomyrdin",
	"It has never been like this and now it is exactly the same again. [Отродясь такого не бывало, и опять то же самое]": "former Russian prime minister Viktor Chernomyrdin",
	"Better than vodka, there is nothing worse. [Лучше водки — хуже нет!]": "former Russian prime minister Viktor Chernomyrdin",
	"We have accomplished all items: from A to B. [Мы выполнили все пункты: от А до Б]": "former Russian prime minister Viktor Chernomyrdin",
	"Don't tell me what I'm doing; I don't want to know.": "Frederico Fellini ",
	"It's all about how you learn from defeat.": "",
	"If there is no reward for taking risk, no one wants to take risk.": "Thomas E. Ricks",
	"The most straightforward way to deceive is to tell lies, which requires a good memory and a vivid imagination for reliable results. People who cannot rely on either of those resort to a more fail-safe technique of simply not telling the truth.": "",
	"each soldier must know his own move and nobody else’s": "Count Alexander Suvorov",
	"A war of ideas where you have the wrong starting assumptions is going to be a costly war.": "Grugq",
	"Internet scale is a weapon.": "Grugq ",
	"4chan is not your personal army, but it is an army.": "Halifax beard ",
	"It is good to know the truth and speak it, but it is better to know the truth and speak of palm trees.": "Arab Proverb",
	"There are two types of warfare: asymmetric and stupid.": "Conrad Crane, us army war college ",
	"A program that has not been specified cannot be incorrect; it can only be surprising.": "Proving a Computer System Secure, W. D. Young, W.E. Boebert and R.Y. Kain, The Scientific Honeyweller (July, 1985), vol. 6, no. 2, pp. 18-27.",
	"Reality is more complex than it seems.": "Susan West. “The New Realism.” Science 84, July/August, 1984, p. 31.",
	"OPSEC tips for hackers: no one is going to go to jail for you. Your friends will betray you.": "The grugq",
	"“Persistent Engagement” was apparently a euphemism for “constant meetings”": "Jason Kikta ",
	"Fight the enemy with the weapon he lacks.": "Count Alexander Suvorov",
	"Roses are Red, Violets are blue. Attackers have budgets, and other constraints too..": "Haroon Meer ",
	"Read it like you stole it. ": "Dave Aitel ",
	"Strong nations hack what they can; weak nations protect what they must.": "@br4s1d4s",
	"The definition of \"gray zone\" is \"whatever the fuck the Russians did this time.\"": "the grugq",
	"Eventually, friction always overcomes momentum.": "BA Friedman",
	"KGB pensioner loses information war to comedian with a smart phone. ": "the grugq",
	"tell me less about capabilities and more about reliabilities.  — On cyber tools ": "Dave Aitel ",
	"cryptography is a tool for reducing a wide variety of issues into key management problems": "Lea Kissner",
	"Cons don't fool us because we're stupid, they fool us because we're human.": "Brian Brushwood",
	"“We should all realize that we can only talk about the bad forgeries, the ones that have been detected; the good ones are still hanging on the walls.”": "Theodore Rousseau ",
	"Hacktivists can't melt steel beams. ": "the grugq",
	"All typos are psyops.": "Active Measures LLC",
	"It is easy to predict an automobile in 1880; it is very hard to predict a traffic problem. The former is really only an extrapolation of the railroad. The latter is something completely novel and unexpected.": "Isaac Asimov",
	"For what so effectually proclaims the madman as the hollow thundering of words —be they never so choice and resplendent —which have no thought or knowledge behind them ?": "Cicero",
	"Verily, an artist in roguery.": "Detective Frank Geyer, on killer HH Holmes.",
	"If you can take advantage of a situation in some way, it's your duty as an American to do it. Why should the race always be to the swift, or the Jumble to the quick-witted? Should they be allowed to win merely because of the gifts God gave them? Well I say, \"Cheating is the gift man gives himself.\"": "Mr Burns, Simpsons Season 8, Mountain of Madness ",
	"Sometimes it's just a book about a few pigs running a farm and having adventures, not everything has to be a political allegory.": "Kxyne",
	"Be quick, but don't hurry.": "Coach John Wooden",
	"Even minutiae should have a place in our collection, for things of a seemingly trifling nature, when enjoined with others of a more serious cast, may lead to valuable conclusion.": "George Washington ",
	"The necessity of procuring good Intelligence is apparent & need not be further urged-All that remains for me to add, is, that you keep the whole matter as secret as possible. For upon Secrecy, Success depends in most Enterprizes of the kind, and for want of it, they are generally defeated, however well planned & promising a favourable issue.": "George Washington ",
	"People pretend data is gold — it isn't; it's uranium – super useful if used correctly and incredibly dangerous to just have laying about.": "Mikko Hypponen",
	"Never underestimate old men in a profession where men die young.": "",
	"Everyone makes mistakes. We are waiting for yours. ": "Dutch security services ",
	"Pwn the means of production.": "Juan Andres Guarre ",
	"Anything not saved will be lost.": "Nintendo quit screen",
	"Humans are more important than Hardware.
Quality is better than Quantity.
Special Operations Forces cannot be mass produced.
Competent Special Operations Forces cannot be created after emergencies occur.
Most Special Operations require non-SOF assistance.": "Special Forces five truths",
	"the app itself doesn't matter. Its existence is a manifestation of the fact that the underlying datasets that drive the app exist. An app is just a pretty skin over a data skeleton.": "Kendra Schaefer ",
	"diem non vacat conterere vanis verbis'

\"there is no time to wear the day away with useless words\"
": "Sen. Tro. 758-9",
	"Part of the art of operational design is knowing where you must win, and where you must simply prevent your enemy from winning": "https://warontherocks.com/2023/02/the-somme-in-the-sky-lessons-from-the-russo-ukrainian-air-war/",
	"no witness to significant changes can recognize them at their beginnings": "Stefan Zweig, Die Welt von Gestern",
	"How fleeting are all human passions compared with the massive continuity of ducks.": "Gaudy Night, Dorothy L. Sayers",
	"Breaking hearts and minds. — subversive propaganda ": "",
	"Utopia is not under the slightest obligation to produce results: its sole function is to allow its devotees to condemn what exists in the name of what does not": "Jean-François Revel",
	"Bitcoin is *retrospectively* a bad way to have done crime…All those transactions you did… are preserved forever… I suppose they have statutes of limitation to worry about, but otherwise, it seems very convenient for the police to have a permanent public record of all the crimes.

https://www.bloomberg.com/opinion/articles/2023-04-13/twitter-gets-into-the-stock-business": "Matt Levine ",
	"Don't depend too much on anyone in this world because even your own shadow leaves you when you are in darkness": "Ibn Taymiyyah",
	"the problem is not the rules: it's that criminals are bribing officials to flout the rules.": "https://www.bangkokpost.com/thailand/general/2580420/superpimp-turned-whistleblower-wont-give-up-fight",
	"If it ain't broke, don't fix it. If it is broke, learn to work around it. ": "https://twitter.com/kathryntewson/status/1688236946932613120?s=61&t=AYKz-sOmaiDr_zGBUyTY_A",
	"The cyber that can be reported is not the real cyber. Counterintelligence principles require truly effective attacks to be kept quiet, by both the attacker and the victim. Note: applies only when CI is followed.": "",
}